spring:
  # PostgreSQL Database Connection Settings
  datasource:
    url: jdbc:postgresql://localhost:5432/vms_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Hibernate Framework Settings
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # Automatically creates/updates tables locally
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # Temporary Spring Security Access (Bypasses the locked login page)
  security:
    user:
      name: admin
      password: password123
